### ISSUE TITLE
Add approval/rejection section for bookings

### ISSUE THREAD

**Issue by rishi-s8** [rishi-s8/book-slots#10]
The admin should be able to see all the awaited booking and have the option to accept and reject it.

**Comment by rishi-s8** [comment]
@Manvi07 add an identifier column for Booking to make this easier.

**Comment by rishi-s8** [comment]
According to the recent review, we also need to include the option to reschedule.

**Comment by Manvi07** [comment]
> @Manvi07 add an identifier column for Booking to make this easier.

Added.

> According to the recent review, we also need to include the option to reschedule.

Added.

**Comment by rishi-s8** [comment]
Commit 4a9416ada293e4073ecf04522606268a2248167c

**Comment by rishi-s8** [comment]
Partially completed right? What is left? @Manvi07

**Comment by Manvi07** [comment]
> Partially completed right? What is left? @Manvi07

We still need an option for the admin to change the status

**Comment by rishi-s8** [comment]
@Manvi07 done right? Should we close this? #24

**Comment by Manvi07** [comment]
> @Manvi07 done right? Should we close this? #24

Sure :)
