### ISSUE TITLE
Add bill to User profile

### ISSUE THREAD

**Issue by Manvi07** [rishi-s8/book-slots#20]
The user profile needs to have a bill stating the paid amount, and the due amount for his bookings. This should have entries only for the confirmed bookings.

**Comment by yashikabaan** [comment]
How will we know the paid amount??

**Comment by rishi-s8** [comment]
A Boolean column in the booking stating it is paid. This can be marked paid by the admin.

**Comment by yashikabaan** [comment]
I am working on this.

**Comment by Manvi07** [comment]
> A Boolean column in the booking stating it is paid. This can be marked paid by the admin.

@rishi-s8 @yashikabaan I think it would be better to have a float/int value(the admin can enter the amount) instead of a boolean, and the due amount can be the difference between the two?

**Comment by rishi-s8** [comment]
@Manvi07 I think that will be Overkill! Let's keep it simple.

**Comment by yashikabaan** [comment]
if someone made a booking for more than a day then what should I have to do???

**Comment by rishi-s8** [comment]
What do you mean?

**Comment by yashikabaan** [comment]
abhi hum log booking dates ke according kr rhe hai na toh agar koi 1 day se jada ke liye book krta hai toh uske liye bill alag hoga na :confused:

**Comment by rishi-s8** [comment]
@yashikabaan What are we doing with booking dates?

**Comment by rishi-s8** [comment]
We don't need to generate a bill, as of now. We just need to show the outstanding amount on the user's profile and for each booking, there should be a column stating it is paid or not. The admin will have the option to mark the booking as paid. The outstanding amount will be computed only for Confirmed and unpaid bookings.

**Comment by yashikabaan** [comment]
Booking...

**Comment by yashikabaan** [comment]
okay

**Comment by Manvi07** [comment]
@yashikabaan any updates on this?

**Comment by yashikabaan** [comment]
I have edited the SQL database and I was trying to implement payment status and changes in admin mode. After that, I can show it on the user profile.
