### ISSUE TITLE
MySQL config is hardcoded

### ISSUE THREAD

**Issue by rishi-s8** [rishi-s8/book-slots#29]
MySQL config is hardcode into the `app.py`. Same for the `secret_key`. These should be taken from the environment (Using `os.environ`).
1. Check if the environment has the variables. If yes, use them.
2. Use the current values as default if some of the environment variable is not set.

**Comment by rishi-s8** [comment]
@Manvi07 @Nivedit24 @yashikabaan, can one of you attend to this?

**Comment by Manvi07** [comment]
How about this?
https://www.mysqltutorial.org/python-connecting-mysql-databases/

**Comment by rishi-s8** [comment]
@Manvi07 Which part?

There are two ways of doing it.

A file config.py that returns these config variables. So, we can put this in the Installation Docs that the config variables need to be updated in the config.py.

The other way to do this is to check the environment variables (that are set using the shell) if they exist (using os.environ). If they don't, use some default values.

**Comment by Manvi07** [comment]
> The other way to do this is to check the environment variables (that are set using the shell) if they exist (using os.environ). If they don't, use some default values.

This way doesn't seem to be portable across different operating systems.

**Comment by Manvi07** [comment]
> A file config.py that returns these config variables. So, we can put this in the Installation Docs that the config variables need to be updated in the config.py.

Can be done :thinking:

**Comment by rishi-s8** [comment]
`config.py` would work just as well.
